baseURL = "https://blog.hausos.xyz/"
languageCode = 'en-us'
title = 'Hausos'
theme = 'hugo-clarity'

[permalinks]
    post = "/:sections/:year/:month/:day/:slug/"

[security]
    enableInlineShortcodes = false

[params]
    enforceLightMode = true
    hasCJKLanguage = true
    showshare = false