baseURL = 'https://zzdcbowl999.github.io/domus/'
canonifyURLs = true
languageCode = 'en-us'
title = 'Hausos'
theme = 'hugo-clarity'

[permalinks]
    post = "/:sections/:year/:month/:day/:filename/"

[security]
    enableInlineShortcodes = false

[params]
    enforceLightMode = true